name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Add Docker service for the job
    services:
      docker:
        image: docker/moby

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Updated to version 2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gameoflife-backend:$(date +%s)
